### ISSUE TITLE
phalcon migration missing

### ISSUE THREAD

**Issue by markhilton** [phalcon/phalcon-compose#33]
when I enter workspace container with: 

docker exec -ti shootflow_app_1 bash

phalcon migration is missing so I have to manually install git://github.com/phalcon/phalcon-devtools.git

**Comment by amq** [comment]
Also, `.phalcon` needs to be a volume, because otherwise it would run all migrations each time.

**Comment by ruudboon** [comment]
Looking at this issue also wondering where the vendor directory should go. 
Should it be a different directory inside application or should we add a volume to the vendor dir in the root.

**Comment by sergeyklay** [comment]
@ruudboon It seems to me better place for PHP's `vendor` dir is `application` directory, e.g.:
```
tree -d
.
├── application
│   ├── cache
│   ├── logs
│   ├── public
│   └── vendor # PHP's vendor
├── bin
├── cache
├── conf
│   └── php
├── data
│   └── mysql
├── docker
│   └── app
│       └── bin
├── logs
├── spec
│   └── localhost
└── vendor # Ruby's 
```

**Comment by sergeyklay** [comment]
@amq Do you suggest to create `.phalcon` inside `application` dir? Could you please explain a bit more?

**Comment by sergeyklay** [comment]
@markhilton Do you suggest to install Phalcon DevTools inside base image?

**Comment by ruudboon** [comment]
@sergeyklay I was already experimenting with this project yesterday. 
I found out that putting the vendor outside the applications dir and not creating the application dir in the first place gives your the possibility to run new-project on the dev-tools. Kinda make sense to me in this project. You run the docker-composer and then with the dev tools you initialise your favourite structure.

**Comment by sergeyklay** [comment]
@ruudboon Well, could you submit the PR?

**Comment by ruudboon** [comment]
@markhilton @amq It's in now. Documentation will be deployed soon. I think we can close this issue now.

**Comment by sergeyklay** [comment]
@ruudboon Thank you for contributing!

**Comment by markhilton** [comment]
@sergeyklay I took a different approach. I installed phalcon/devtools as a package through the composer, but had to add a script to symlink it when container starts up.
