### ISSUE TITLE
Could not connect to postgresql

### ISSUE THREAD

**Issue by Kachit** [phalcon/phalcon-compose#34]
My credentials:
gui: Navicat
host:127.0.0.1
port:5432
user:phalcon
password:secret
db:postgres

I try to connect to postgres after run container and catch this error (could not connect to server: Connection refused
    Is the server running on host "127.0.0.1" and accepting
    TCP/IP connections on port 5432?)
Connect to Mysql is correct

**Comment by sergeyklay** [comment]
I'll take a look today

**Comment by sergeyklay** [comment]
Fixed in the latest release
