### ISSUE TITLE
how to add my old site to container

### ISSUE THREAD

**Issue by kideny** [phalcon/phalcon-compose#44]
i  have a old site ,  how to add my site to container ?

**Comment by sergeyklay** [comment]
Just use project root as website root https://github.com/phalcon/phalcon-compose/blob/master/docker-compose.yml#L105

**Comment by kideny** [comment]
i hope add multi site to container.

**Comment by sergeyklay** [comment]
Actually you can't. Phalcon Compose designed to be a container for one application (site). However, you can run as many copies of Phalcon Compose as you need. In this case you'll need to modify ports section in each `docker-compose.yml`. For example:
```yml
ports:
      - "8081:80"
      - "4431:443"
```

```yml
ports:
      - "8082:80"
      - "4432:443"
```

```yml
ports:
      - "8083:80"
      - "4433:443"
```

```yml
ports:
      - "8084:80"
      - "4434:443"
```

Note to avoid collision you'll need to modify all ports eg `elasticsearch`, `aerospike`, etc.

**Comment by kideny** [comment]
tks , you answer . i love you forever !
