### ISSUE TITLE
503 Service Unavailable occurs when calling findFirst()

### ISSUE THREAD

**Issue by tommykamkcm** [phalcon/phalcon-compose#46]
Hi everyone

I'm experiencing an issue when trying to fetch data using findFirst(). Here is the code that leads to 503 error:
```php
$user = self::findFirst(array(
            'conditions' => "email = :email: AND is_active = :is_active:",
            'bind' => array(
               'email' => $email,
               'is_active' => 1
            )
         ));
```

After a bunch of tests, I eventually found out what caused the 503 error. If I changed the code to remove `is_active = 1` i.e. column's name contains `_`, I could see the next page:
```php
$user = self::findFirst(array(
            'conditions' => "email = :email:",
            'bind' => array(
               'email' => $email
            )
         ));
```

One thing that I would like to mention is if I've tried to run the same application on Vagrant (ubuntu), but I could not replicate the issue. I reckon phalcon may not be fully compatible with docker.

Below are the error logs of the `app` and `db` containers

```
docker logs xxx-app
[proxy_fcgi:error] [pid 91:tid 140550103619328] [client 192.168.99.1:62364] AH01067: Failed to read FastCGI header, referer: http://192.168.99.102/xxx/xxx
[proxy_fcgi:error] [pid 91:tid 140550103619328] (104)Connection reset by peer: [client 192.168.99.1:62364] AH01075: Error dispatching request to : , referer: http://192.168.99.102/xxx/xxx docker.vm:80 192.168.99.1 - - [16/Jan/2018:10:37:33 +0000] "POST /admin/login HTTP/1.1" 503 569 "http://192.168.99.102/xxx/xxx" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
[httpd:access] 192.168.99.102:80 192.168.99.1 - - [16/Jan/2018:10:37:33 +0000] "POST /xxx/xxx HTTP/1.1" 503 bytesIn:756 bytesOut:569 reqTime:0
WARNING: [pool www] child 687 exited on signal 4 (SIGILL) after 166.625066 seconds from start
```

```
docker logs xxx-db
[Note] Aborted connection 44 to db: 'xxx' user: 'xxx' host: '172.18.0.1' (Got an error reading communication packets)
```

Thanks in advance!

**Comment by sergeyklay** [comment]
First of all I would note that this is not Phalcon Compose issue. It's more like an issue with framework. But this project doesn't responsible for framework's issues. Feel free to open a new issue [in the appropriate repository](https://github.com/phalcon/cphalcon) with code to reproduce, relevant info and provided core dump.
